import { KpiCategory, MeasurementDirection, ReportingFrequency, KpiPeriodStatus } from "@prisma/client";

export const MOCK_DEFAULT_KPIS = [
  {
    id: "kpi-str-01",
    code: "KPI-STR-01",
    name: "Tỷ lệ thực hiện kế hoạch chiến lược năm",
    category: KpiCategory.STRATEGIC,
    purpose: "Đánh giá mức độ hoàn thành các mục tiêu chiến lược nhà trường giao cho phân hiệu",
    formula: "(Số mục tiêu đạt chuẩn / Tổng số mục tiêu giao) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Mục tiêu chiến lược (QualityObjective)",
    frequency: ReportingFrequency.SEMESTER,
    weight: 10,
    baselineValue: 80,
    targetValue: 95,
    responsiblePerson: "Hiệu trưởng / Ban Giám hiệu",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-edu-01",
    code: "KPI-EDU-01",
    name: "Tỷ lệ học sinh đạt chuẩn học tập theo Thông tư 27 (Điểm số ≥ 5.0)",
    category: KpiCategory.EDUCATIONAL_QUALITY,
    purpose: "Nâng cao chất lượng học tập toàn trường theo quy chế đánh giá học sinh tiểu học (TT 27/2020/TT-BGDĐT)",
    formula: "(Số bài kiểm tra định kỳ có điểm ≥ 5.0 / Tổng số bài kiểm tra) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Điểm số & Học bạ điện tử (Grade)",
    frequency: ReportingFrequency.SEMESTER,
    weight: 15,
    baselineValue: 35,
    targetValue: 95,
    responsiblePerson: "Phó Hiệu trưởng Chuyên môn",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-pro-01",
    code: "KPI-PRO-01",
    name: "Tỷ lệ giáo án điện tử được phê duyệt đúng hạn",
    category: KpiCategory.PROFESSIONAL,
    purpose: "Thúc đẩy đổi mới phương pháp giảng dạy và đảm bảo kỷ cương soạn giảng",
    formula: "(Số giáo án được Tổ trưởng/BGH phê duyệt đúng hạn / Tổng số giáo án đã nộp) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Giáo án điện tử (LessonPlan)",
    frequency: ReportingFrequency.MONTHLY,
    weight: 10,
    baselineValue: 70,
    targetValue: 95,
    responsiblePerson: "Tổ trưởng Chuyên môn",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-sta-01",
    code: "KPI-STA-01",
    name: "Tỷ lệ giáo viên tham gia bồi dưỡng chuyên môn thường xuyên",
    category: KpiCategory.STAFF_PERSONNEL,
    purpose: "Nâng cao trình độ đội ngũ nhà giáo và năng lực sư phạm",
    formula: "(Số giáo viên hoàn thành bồi dưỡng / Tổng số giáo viên) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Hồ sơ giáo viên & Nhân sự (Teacher)",
    frequency: ReportingFrequency.QUARTERLY,
    weight: 8,
    baselineValue: 85,
    targetValue: 100,
    responsiblePerson: "Phó Hiệu trưởng Phụ trách",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-stu-01",
    code: "KPI-STU-01",
    name: "Tỷ lệ chuyên cần của học sinh",
    category: KpiCategory.STUDENT,
    purpose: "Đảm bảo duy trì sĩ số và chuyên cần đến lớp hàng ngày của học sinh",
    formula: "(Số lượt học sinh có mặt / Tổng số lượt điểm danh) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Điểm danh điện tử (Attendance)",
    frequency: ReportingFrequency.MONTHLY,
    weight: 8,
    baselineValue: 90,
    targetValue: 98,
    responsiblePerson: "Giáo viên Chủ nhiệm & Tổng phụ trách",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-dig-01",
    code: "KPI-DIG-01",
    name: "Mức độ hoàn thiện cơ sở dữ liệu ngành & Sổ sách điện tử",
    category: KpiCategory.DIGITAL_TRANSFORMATION,
    purpose: "Đảm bảo 100% học bạ, giáo án, sổ điểm số hóa đúng hạn",
    formula: "(Số hồ sơ số hóa được duyệt / Tổng hồ sơ) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Hồ sơ số hóa (LessonPlan & Digital Records)",
    frequency: ReportingFrequency.MONTHLY,
    weight: 8,
    baselineValue: 80,
    targetValue: 100,
    responsiblePerson: "Cán bộ CNTT",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-fin-01",
    code: "KPI-FIN-01",
    name: "Tỷ lệ giải ngân ngân sách giáo dục",
    category: KpiCategory.FINANCIAL,
    purpose: "Sử dụng hiệu quả nguồn vốn được giao theo đúng quy định tài chính",
    formula: "(Kinh phí giải ngân thực tế / Kinh phí dự toán được giao) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "Sổ sách Dự toán & Giải ngân tài chính (Budget/Accounting)",
    frequency: ReportingFrequency.QUARTERLY,
    weight: 8,
    baselineValue: 85,
    targetValue: 98,
    responsiblePerson: "Kế toán trưởng",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-ast-01",
    code: "KPI-AST-01",
    name: "Tỷ lệ thiết bị dạy học được bảo dưỡng & sử dụng tốt",
    category: KpiCategory.ASSETS,
    purpose: "Quản lý và khai thác hiệu quả tài sản phòng học và trang thiết bị",
    formula: "(Số thiết bị hoạt động Tốt/Khá / Tổng số thiết bị kiểm kê) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Kiểm kê thiết bị dạy học (Equipment)",
    frequency: ReportingFrequency.MONTHLY,
    weight: 6,
    baselineValue: 88,
    targetValue: 98,
    responsiblePerson: "Cán bộ Thiết bị",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-fac-01",
    code: "KPI-FAC-01",
    name: "Đạt tiêu chuẩn phòng học xanh - sạch - đẹp",
    category: KpiCategory.FACILITIES,
    purpose: "Đảm bảo cảnh quan và môi trường học tập tốt nhất",
    formula: "Đánh giá đạt / không đạt (1 = Đạt, 0 = Không)",
    unit: "Điểm",
    direction: MeasurementDirection.PASS_FAIL,
    dataSource: "CSDL Cơ sở vật chất & Phòng học (Equipment/Facilities)",
    frequency: ReportingFrequency.MONTHLY,
    weight: 5,
    baselineValue: 1,
    targetValue: 1,
    responsiblePerson: "Trưởng ban Cơ sở vật chất",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-saf-01",
    code: "KPI-SAF-01",
    name: "Số sự cố an toàn trường học, PCCC & Vi phạm kỷ luật",
    category: KpiCategory.SCHOOL_SAFETY,
    purpose: "Đảm bảo tuyệt đối an toàn cho GV & Học sinh (Chỉ tiêu không xảy ra sự cố)",
    formula: "Tổng số vụ việc mất an toàn hoặc vi phạm kỷ luật xảy ra (0 vụ = 100%)",
    unit: "vụ",
    direction: MeasurementDirection.LOWER_BETTER,
    dataSource: "CSDL Nhật ký Kỷ luật & Sự cố an toàn (Incident)",
    frequency: ReportingFrequency.MONTHLY,
    weight: 7,
    baselineValue: 0,
    targetValue: 0,
    responsiblePerson: "Trưởng ban An ninh & Giám thị",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-rel-01",
    code: "KPI-REL-01",
    name: "Tỷ lệ giải quyết ý kiến & phản hồi của phụ huynh",
    category: KpiCategory.SCHOOL_RELATIONS,
    purpose: "Tăng cường gắn kết giữa gia đình và nhà trường, giải quyết kịp thời kiến nghị",
    formula: "(Số ý kiến phụ huynh đã được phản hồi / Tổng số ý kiến tiếp nhận) * 100",
    unit: "%",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Ý kiến & Phản hồi phụ huynh (ParentFeedback)",
    frequency: ReportingFrequency.MONTHLY,
    weight: 8,
    baselineValue: 80,
    targetValue: 95,
    responsiblePerson: "Ban Giám hiệu & GVCN",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "kpi-inn-01",
    code: "KPI-INN-01",
    name: "Số lượng sáng kiến kinh nghiệm & Khen thưởng thi đua",
    category: KpiCategory.INNOVATION,
    purpose: "Khuyến khích nghiên cứu khoa học sư phạm ứng dụng và thi đua dạy tốt",
    formula: "Tổng số đề tài SKKN và quyết định khen thưởng được công nhận",
    unit: "đề tài",
    direction: MeasurementDirection.HIGHER_BETTER,
    dataSource: "CSDL Khen thưởng & SKKN (Commendation)",
    frequency: ReportingFrequency.YEARLY,
    weight: 5,
    baselineValue: 2,
    targetValue: 5,
    responsiblePerson: "Hội đồng Thi đua Khen thưởng",
    scope: "ALL",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_CAMPUSES = [
  { id: "cmp_trungtam", name: "Điểm trường Trung tâm (Phố Lu)", address: "Thị trấn Phố Lu, Huyện Bảo Thắng" },
  { id: "cmp_sonha1", name: "Phân hiệu Sơn Hà 1", address: "Thôn Sơn Hà 1, Xã Sơn Hà" },
  { id: "cmp_sonha2", name: "Phân hiệu Sơn Hà 2", address: "Thôn Sơn Hà 2, Xã Sơn Hà" },
  { id: "cmp_sonhai", name: "Phân hiệu Sơn Hải", address: "Thôn Sơn Hải, Xã Sơn Hà" },
  { id: "cmp_pholu3", name: "Phân hiệu Phố Lu 3", address: "Khu 3, Thị trấn Phố Lu" },
  { id: "cmp_antien", name: "Phân hiệu An Tiến", address: "Thôn An Tiến, Xã Sơn Hải" },
];

export const MOCK_PERIODS = [
  {
    id: "prd_2026_hk1",
    title: "Chu kỳ Đánh giá Mục tiêu KPI Học kỳ 1 Năm học 2026-2027",
    year: 2026,
    periodType: ReportingFrequency.SEMESTER,
    campusId: null,
    status: KpiPeriodStatus.SUBMITTED,
    overallScore: 92.5,
    createdAt: new Date(),
    updatedAt: new Date(),
    campus: null,
    approvalLogs: [],
    unlockLogs: [],
  },
  {
    id: "prd_2025_full",
    title: "Chu kỳ Đánh giá Toàn diện KPI Năm học 2025-2026",
    year: 2025,
    periodType: ReportingFrequency.YEARLY,
    campusId: null,
    status: KpiPeriodStatus.APPROVED,
    overallScore: 96.8,
    createdAt: new Date(),
    updatedAt: new Date(),
    campus: null,
    approvalLogs: [],
    unlockLogs: [],
  },
];

export function filterMockCatalogs(search?: string, category?: string, isActive?: boolean) {
  return MOCK_DEFAULT_KPIS.filter((item) => {
    if (isActive !== undefined && item.isActive !== isActive) return false;
    if (category && category !== "ALL" && item.category !== category) return false;
    if (search && search.trim()) {
      const q = search.toLowerCase();
      const match =
        item.code.toLowerCase().includes(q) ||
        item.name.toLowerCase().includes(q) ||
        item.responsiblePerson.toLowerCase().includes(q);
      if (!match) return false;
    }
    return true;
  });
}
